
homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret hass_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml
  customize_glob: !include customizeglob.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/
# Enables configuration UI
config:

lovelace:
  mode: yaml

http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key_path
  base_url: !secret home_address

api:
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

logger:
  default: info
  
# Discover some devices automatically
discovery:

# handles the db
recorder:
  purge_keep_days: 15
  
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

zwave:
    usb_path: /dev/ttyACM0
 
 # Text to speech
tts:
  - platform: google_translate
    service_name: google_say

light:
  - platform: group
    name: Kitchen Lights
    entities:
      - light.kitchen_dimmer_level
      - light.kitchen_led_strip
  - platform: group
    name: Bathroom Lights
    entities:
      - light.bathroom_dimmer_level

media_player: !include mediaplayers.yaml
weblink: !include weblinks.yaml   
shell_command: !include shell_commands.yaml
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/
scene: !include scenes.yaml
group: !include_dir_merge_named groups/
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
binary_sensor: !include_dir_merge_list binary_sensors/

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

# dark mode
input_boolean:
  night_mode:
    name: When night mode is set
    initial: off
    icon: mdi:weather-night

system_health:

device_tracker:
  - platform: huesensor
  
hacs:
  token: !secret hacs_token
  appdaemon: true
  python_script: true
  theme: true
