- platform: kodi
  name: raw_kodi
  host: !secret ip_kodi_player
  port: !secret port_kodi_player

- platform: universal
  name: Kodi
  children:
    - media_player.raw_kodi
  state_template: >
    {% if is_state('switch.kodi_switch', 'off') or is_state('switch.projector_cli', 'off') %}
    off
    {% else %}
    {{ states('media_player.raw_kodi') }}
    {% endif %}
  commands:
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.watch_film
    turn_off:
      service: switch.turn_off
      data:
        entity_id: switch.watch_film
  attributes:
    state: switch.watch_film
    
# Note: needs 2 separate activations from 2 separate browser or different IPs maybe
- platform: spotify
  client_id: !secret client_id_spotify_player
  client_secret: !secret secret_spotify_player
  name: VeroSpotify
  # must have a cache path with absolute path to make it work https://community.home-assistant.io/t/support-for-multiple-spotify-accounts/16117/18
  cache_path: /config/verospotity.cache

- platform: spotify
  client_id: !secret client_id_spotify_player_paule
  client_secret: !secret secret_spotify_player_paule
  name: VeroSpotify_Paule
  cache_path: /config/verospotity_paule.cache

# add the universal mediaplayer to override the turn_on/off actions not available in spotify component
- platform: universal
  name: Spotify
  children:
    - media_player.verospotify
  state_template: >
    {% if is_state('switch.kodi_switch', 'off')  %}
    off
    {% elif state_attr('media_player.verospotify', 'source') == 'raspotify (osmc)' or 
        state_attr('media_player.verospotify2', 'source') == 'raspotify (osmc)' -%}
      {% if is_state('media_player.verospotify', 'playing') or is_state('media_player.verospotify_2', 'playing') %}
      playing
      {% endif %}
    {% else %}
    idle
    {% endif %}
  commands:
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.kodi_switch
    turn_off:
      service: media_player.media_play_pause
      data:
        entity_id: media_player.verospotify
  attributes:
    state: switch.kodi_switch
