- platform: kodi
  name: raw_kodi
  host: !secret ip_kodi_player
  port: !secret port_kodi_player

- platform: universal
  name: Kodi
  children:
    - media_player.raw_kodi
  state_template: >
    {% if is_state('switch.kodi_switch', 'off') or is_state('switch.projector_cli', 'off') %}
    off
    {% else %}
    {{ states('media_player.raw_kodi') }}
    {% endif %}
  commands:
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.watch_film
    turn_off:
      service: switch.turn_off
      data:
        entity_id: switch.watch_film
  attributes:
    state: switch.watch_film
    
# add the universal mediaplayer to override the turn_on/off actions not available in spotify component
- platform: universal
  name: Spotify
  children:
    - media_player.spotify_slyou666
  state_template: >
    {% if is_state('switch.kodi_switch', 'off')  %}
    off
    {% elif state_attr('media_player.spotify_slyou666', 'source') == 'raspotify (osmc)' or 
        state_attr('media_player.paule_spotify', 'source') == 'raspotify (osmc)' -%}
      {% if is_state('media_player.spotify_slyou666', 'playing') or is_state('media_player.paule_spotify', 'playing') %}
      playing
      {% else %}
      idle
      {% endif %}
    {% else %}
    idle
    {% endif %}
  commands:
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.kodi_switch
    turn_off:
      service: media_player.media_play_pause
      data:
        entity_id: media_player.spotify_slyou666
  attributes:
    state: switch.kodi_switch
