resources:
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
    type: module

title: Home
views:
  - title: Main
    badges: []
    id: main
    icon: mdi:home
    # panel: false
    cards:
      # - type: custom:compact-custom-header
      - type: glance
        entities:
          - entity: scene.all_lights_off
            icon: mdi:flashlight-off
            name: Lights Off
            tap_action:
              action: call-service
              service: light.turn_off
              service_data: 
                entity_id: all
      - type: horizontal-stack
        cards:
          - type: custom:mini-media-player
            entity: media_player.spotify
            icon: mdi:spotify
            artwork: cover
            info: short
            toggle_power: false
            hide:
              mute: true
              power_state: false
          - type: custom:mini-media-player
            entity: media_player.kodi
            icon: mdi:kodi
            artwork: cover
            info: short
            toggle_power: false
            hide:
              mute: true
              power_state: false
      - type: glance
        entities:
          - entity: switch.pcsylvain
            icon: mdi:laptop
            tap_action:
              action: toggle
          - entity: switch.printer_switch
            icon: mdi:printer
            tap_action:
              action: toggle
          - entity: switch.nas
            icon: mdi:nas
            tap_action:
              action: toggle
      - type: entities
        title: Lights
        entities:
          - type: section
          - type: custom:slider-entity-row
            entity: light.kitchen_lights
            toggle: true
          - type: custom:slider-entity-row
            entity: light.bathroom_lights
            toggle: true
          - type: custom:slider-entity-row
            entity: light.entrance_dimmer_level
            toggle: true
          - type: custom:slider-entity-row
            entity: light.bedroom_main
            toggle: true
          - type: custom:slider-entity-row
            entity: light.livroom_main
            toggle: true

      - type: horizontal-stack
        cards:
        - type: custom:mini-graph-card
          name: Kitchen/Salon
          entities:
            - entity: sensor.kitchen_motion_sensor_temperature
              name: Fibaro
            - entity: sensor.cuisine_salon_temperature
              name: Thermostat
            - entity: sensor.cuisine_salon_humidity
              name: Humidity
              color: blue
              y_axis: secondary
          hours_to_show: 168
          points_per_hour: 0.25
          show:
            labels: true
            labels_secondary: true
            state: true
            graph: line
          color_thresholds:
            - value: 10
              color: blue
            - value: 20
              color: green
            - value: 22
              color: orange
            - value: 23.5
              color: red          
      - type: horizontal-stack
        cards:
        - type: custom:mini-graph-card
          name: Entrance
          entities:
            - entity: sensor.entrance_motion_sensor_temperature              
          hours_to_show: 168
          points_per_hour: 0.25
          show:
            labels: true
            state: true
            graph: line
          color_thresholds:
            - value: 10
              color: blue
            - value: 20
              color: green
            - value: 22
              color: orange
            - value: 23.5
              color: red
        - type: custom:mini-graph-card
          name: Bathroom
          entities:
            - entity: sensor.bathroom_motion_sensor_temperature
              name: Fibaro
            - entity: sensor.salle_de_bain_temperature
              name: Thermostat
            - entity: sensor.salle_de_bain_humidity
              name: Humidity
              color: blue
              y_axis: secondary
          hours_to_show: 168
          points_per_hour: 0.25
          show:
            labels: true
            labels_secondary: true
            state: true
            graph: line
          color_thresholds:
            - value: 10
              color: blue
            - value: 20
              color: green
            - value: 22
              color: orange
            - value: 23.5
              color: red
      - type: horizontal-stack      
        cards:
        - type: custom:mini-graph-card
          name: Bedroom
          entities:
            - entity: sensor.bedroom_motion_sensor_temperature
              name: Fibaro
            - entity: sensor.parents_temperature
              name: Thermostat
            - entity: sensor.parents_humidity
              name: Humidity
              color: blue
              y_axis: secondary
          hours_to_show: 168
          points_per_hour: 0.25
          show:
            labels: true
            labels_secondary: true
            state: true
            graph: line
          color_thresholds:
            - value: 10
              color: blue
            - value: 20
              color: green
            - value: 22
              color: orange
            - value: 23.5
              color: red
        - type: custom:mini-graph-card
          name: Liv room
          entities:
            - entity: sensor.livroom_motion_sensor_temperature
              name: Fibaro
            - entity: sensor.liv_temperature
              name: Thermostat
            - entity: sensor.liv_humidity
              name: Humidity
              color: blue
              y_axis: secondary
          hours_to_show: 168
          points_per_hour: 0.25
          show:
            labels: true
            labels_secondary: true
            state: true
            graph: line
          color_thresholds:
            - value: 10
              color: blue
            - value: 20
              color: green
            - value: 22
              color: orange
            - value: 23.5
              color: red     
      - type: horizontal-stack
        cards:
          - type: thermostat
            entity: climate.cuisine_salon
            name: Kitchen/Salon
          - type: thermostat
            entity: climate.parents
            name: Bedroom
      - type: horizontal-stack
        cards:
          - type: thermostat
            entity: climate.liv
            name: Liv room
          - type: thermostat
            entity: climate.salle_de_bain
            name: Bathroom
              

  - title: Monitoring
    icon: mdi:tune
    id: monitoring    
    cards:
      # - type: custom:compact-custom-header
      - type: entity-filter
        entities:
          - binary_sensor.sunrise_router
          - binary_sensor.pc_sylvain
          - binary_sensor.vero_4k
          - binary_sensor.nas
          - binary_sensor.kodi_switch
          - binary_sensor.printer_switch
          - binary_sensor.pc_switch
        state_filter:
          - "on"
        card:
          type: glance
          title: Systems on the network

      - type: custom:mini-graph-card
        name: Internet connectivity
        icon: mdi:network
        unit: ms
        entities:
          - entity:  sensor.internet_connectivity
      - type: custom:mini-graph-card
        name: Intranet
        icon: mdi:network
        unit: ms
        entities:
          - entity: sensor.pc_sylvain_connectivity
          - entity: sensor.nas_connectivity
          - entity: sensor.vero_4k_connectivity
      - type: custom:mini-graph-card
        title: Raspberry
        icon: mdi:raspberry
        entities:
          - entity: sensor.processor_use
          - entity: sensor.disk_use_percent
          - entity: sensor.memory_free
            y_axis: secondary
          - entity: sensor.disk_free
            y_axis: secondary
      - type: entities
        title: Raspberry
        show_header_toggle: false
        entities:
          - entity: sensor.last_boot
          - entity: sensor.network_in_enxb827eb962127
          - entity: sensor.network_throughput_in_enxb827eb962127
          - entity: sensor.network_out_enxb827eb962127
          - entity: sensor.network_throughput_out_enxb827eb962127
          - entity: sensor.processor_use
          - entity: sensor.disk_use_percent
          - entity: sensor.disk_free
          - entity: sensor.memory_free
      - type: custom:mini-graph-card
        title: NAS Synology
        icon: mdi:nas
        entities:
          - entity: sensor.synology_dsm_network_up
          - entity: sensor.synology_dsm_network_down
          - entity: sensor.synology_dsm_cpu_load_total
            y_axis: secondary
          - entity: sensor.synology_dsm_memory_usage_real
            y_axis: secondary
          - entity: sensor.synology_dsm_volume_used_volume_1
            y_axis: secondary
      - type: entities
        title: NAS Synology
        show_header_toggle: false
        entities:
          - entity: sensor.synology_dsm_network_up
          - entity: sensor.synology_dsm_network_down
          - entity: sensor.synology_dsm_cpu_load_total
          - entity: sensor.synology_dsm_memory_usage_real
          - entity: sensor.synology_dsm_status_smart_sda
          - entity: sensor.synology_dsm_status_smart_sdb
          - entity: sensor.synology_dsm_status_smart_sdc
          - entity: sensor.synology_dsm_status_smart_sdd
          - entity: sensor.synology_dsm_volume_used_volume_1
      - type: custom:mini-graph-card
        name: Fibaro batteries
        icon: mdi:battery
        unit: "%"
        lower_bound: 0
        upper_bound: 100
        show:
          labels: true
          # fill: false
          name_adaptive_color: true
          graph: line
        color_thresholds:
          - value: 0
            color: red
          - value: 30
            color: yellow
          - value: 70
            color: green

        entities:
        - entity: sensor.bathroom_fibaro_battery
          # scale: 30px
          # from: bottom
          # min: 0
          # max: 100
          # severity:
          #   - value: 20
          #     style: 'var(--label-badge-red)'
          #   - value: 50
          #     style: 'var(--label-badge-yellow)'
          #   - value: 100
          #     style: 'var(--label-badge-green)'
        - entity: sensor.bedroom_fibaro_battery
        - entity: sensor.entrance_fibaro_battery
        - entity: sensor.kitchen_fibaro_battery
        - entity: sensor.livroom_fibaro_battery
      - type: custom:mini-graph-card
        name: Light intensity
        icon: mdi:spotlight-beam
        unit: lm
        entities:
          - entity: sensor.kitchen_motion_sensor_luminance
          - entity: sensor.bathroom_motion_sensor_luminance
          - entity: sensor.bedroom_motion_sensor_luminance
          - entity: sensor.livroom_motion_sensor_luminance

  - title: Advanced
    icon: mdi:settings
    id: advanced
    cards:
      - type: glance
        entities:
            - entity: sensor.hacs
      - type: custom:fold-entity-row
        head: group.all_automations
      - type: custom:fold-entity-row
        head: group.all_switches
      - type: custom:fold-entity-row
        head: group.all_sensors