- platform: synologydsm
  host: !secret ip_nas
  username: !secret separate_user_nas
  password: !secret separate_user_password
  monitored_conditions:
    - cpu_total_load
    - memory_real_usage
    - network_up
    - network_down
    - disk_smart_status
    - volume_percentage_used