- platform: template
  sensors:
    nas_connectivity:
      friendly_name: "NAS Connectivity"
      entity_id: binary_sensor.nas
      icon_template: mdi-network
      value_template: "{{ states.binary_sensor.nas.attributes.round_trip_time_avg }}"
