- platform: synologydsm
  ssl: false
  host: !secret ip_nas
  port: !secret port_nas
  username: !secret separate_user_nas
  password: !secret separate_user_password
  monitored_conditions:
    - cpu_total_load
    - memory_real_usage
    - network_up
    - network_down
    - disk_smart_status
    - volume_percentage_used

- platform: template
  sensors:
    nas_connectivity:
      friendly_name: "NAS Connectivity"
      entity_id:  binary_sensor.nas
      icon_template: mdi-network
      value_template: "{{ states.binary_sensor.nas.attributes.round_trip_time_avg }}" 