- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_free
      arg: /
    - type: memory_free
    - type: network_in
      arg: enxb827eb962127
    - type: throughput_network_in
      arg: enxb827eb962127
    - type: network_out
      arg: enxb827eb962127
    - type: throughput_network_out
      arg: enxb827eb962127
    - type: processor_use
    - type: last_boot

- platform: rpi_power
  text_state: true