- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_free
      arg: /
    - type: memory_free
    - type: memory_use_percent
    - type: network_in      
    - type: throughput_network_in      
    - type: packets_in
    - type: network_out      
    - type: throughput_network_out      
    - type: packets_out
    - type: processor_use
    - type: last_boot

- platform: rpi_power
  text_state: true