- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_free
      arg: /
    - type: memory_free
    - type: network_in
    - type: network_out
    - type: processor_use
    - type: last_boot